export type Field = {
  key: string;
  label: string;
  type?: string;
  options?: string[];
  required?: boolean;
};
export const fields: Record<string, Field[]> = {
  class: [
    { key: 'name', label: 'Class name', required: true },
    { key: 'color', label: 'Class colour', type: 'color', required: true },
    {
      key: 'weekdays',
      label: 'Lesson weekdays',
      type: 'weekdays',
      required: true,
    },
    {
      key: 'archived',
      label: 'Archive class (keep attendance history)',
      type: 'checkbox',
    },
  ],
  catalogue: [
    { key: 'label', label: 'Package name', required: true },
    { key: 'sessions', label: 'Sessions', type: 'number', required: true },
    {
      key: 'price',
      label: 'Catalogue price (VND)',
      type: 'number',
      required: true,
    },
    { key: 'active', label: 'Available for new agreements', type: 'checkbox' },
    { key: 'notes', label: 'Notes', type: 'textarea' },
  ],
  receipt: [
    {
      key: 'date',
      label: 'Payment date / Ngày thu',
      type: 'date',
      required: true,
    },
    { key: 'name', label: 'Payer / Người nộp', required: true },
    { key: 'studentId', label: 'Student / Học viên', type: 'student' },
    {
      key: 'packageId',
      label: 'Package receiving this payment',
      type: 'package',
    },
    {
      key: 'purpose',
      label: 'Purpose',
      type: 'select',
      options: ['Tuition', 'Deposit', 'Books', 'Other income'],
    },
    {
      key: 'amount',
      label: 'Amount received / Số tiền (VND)',
      type: 'number',
      required: true,
    },
    { key: 'account', label: 'Receiving account', required: true },
    { key: 'reference', label: 'Bank reference / Ghi chú' },
    { key: 'description', label: 'Description' },
    {
      key: 'reconciled',
      label: 'Matched to bank statement / cash record',
      type: 'checkbox',
    },
  ],
  expense: [
    {
      key: 'date',
      label: 'Payment date / Ngày chi',
      type: 'date',
      required: true,
    },
    {
      key: 'category',
      label: 'Category / Nhóm',
      type: 'select',
      options: [
        'Payroll',
        'Rent',
        'Utilities',
        'Teaching',
        'Books',
        'Marketing',
        'Insurance',
        'Bank fees',
        'Office',
        'Other',
      ],
    },
    { key: 'description', label: 'Description / Nội dung', required: true },
    {
      key: 'amount',
      label: 'Amount paid / Số tiền (VND)',
      type: 'number',
      required: true,
    },
    { key: 'account', label: 'Paying account', required: true },
    { key: 'reference', label: 'Invoice / reference' },
    {
      key: 'reconciled',
      label: 'Matched to bank statement / cash record',
      type: 'checkbox',
    },
  ],
  student: [
    { key: 'name', label: 'Student name / Họ tên', required: true },
    { key: 'preferredName', label: 'English / preferred name' },
    { key: 'birthDate', label: 'Date of birth / Ngày sinh', type: 'date' },
    { key: 'school', label: 'School / Trường học' },
    {
      key: 'classId',
      label: 'Home class / Lớp chính',
      type: 'class',
      required: true,
    },
    {
      key: 'status',
      label: 'Status / Trạng thái',
      type: 'select',
      options: [
        'Active',
        'Paused',
        'Stopped',
        'Roster only',
        'Free',
        'Ends without renewal',
      ],
    },
    { key: 'parent', label: 'Parent / Phụ huynh' },
    { key: 'phone', label: 'Phone / Điện thoại' },
    { key: 'parentEmail', label: 'Parent email', type: 'email' },
    { key: 'zalo', label: 'Zalo contact' },
    { key: 'secondParent', label: 'Second / emergency contact' },
    { key: 'secondPhone', label: 'Second contact phone', type: 'tel' },
    { key: 'address', label: 'Address / Địa chỉ' },
    {
      key: 'enrollmentDate',
      label: 'Enrollment date / Ngày nhập học',
      type: 'date',
    },
    { key: 'pauseFrom', label: 'Pause from', type: 'date' },
    { key: 'resumeDate', label: 'Resume on', type: 'date' },
    {
      key: 'learningGoals',
      label: 'Learning goals / Mục tiêu học tập',
      type: 'textarea',
    },
    { key: 'notes', label: 'Notes', type: 'textarea' },
  ],
  package: [
    {
      key: 'studentId',
      label: 'Student / Học viên',
      type: 'student',
      required: true,
    },
    { key: 'sessions', label: 'Package / Gói học', type: 'price' },
    {
      key: 'startDate',
      label: 'Start date / Bắt đầu',
      type: 'date',
      required: true,
    },
    {
      key: 'agreedFee',
      label: 'Actual agreed fee after discount (VND)',
      type: 'number',
      required: true,
    },
    { key: 'dueDate', label: 'Payment due date / Hạn đóng', type: 'date' },
    {
      key: 'scope',
      label: 'Sessions apply to',
      type: 'select',
      options: ['all', 'class'],
    },
    {
      key: 'classId',
      label: 'Class (for class-specific packages)',
      type: 'class',
    },
    { key: 'notes', label: 'Agreement notes', type: 'textarea' },
  ],
  makeup: [
    {
      key: 'studentId',
      label: 'Student / Học viên',
      type: 'student',
      required: true,
    },
    {
      key: 'absenceId',
      label: 'Original absence / Buổi nghỉ',
      type: 'absence',
      required: true,
    },
    {
      key: 'date',
      label: 'Makeup date / Ngày bù',
      type: 'date',
      required: true,
    },
    { key: 'makeupClass', label: 'Makeup class or location' },
    { key: 'teacher', label: 'Teacher / Giáo viên' },
    {
      key: 'status',
      label: 'Status',
      type: 'select',
      options: ['Planned', 'Completed', 'Cancelled'],
    },
    { key: 'notes', label: 'Lesson content', type: 'textarea' },
  ],
  support: [
    {
      key: 'studentId',
      label: 'Student / Học viên',
      type: 'student',
      required: true,
    },
    { key: 'classId', label: 'Class / Lớp', type: 'class', required: true },
    {
      key: 'date',
      label: 'Support date / Ngày học',
      type: 'date',
      required: true,
    },
    { key: 'teacher', label: 'Teacher / Giáo viên' },
    {
      key: 'status',
      label: 'Status',
      type: 'select',
      options: ['Planned', 'Completed', 'Cancelled'],
    },
    {
      key: 'notes',
      label: 'Lesson content / Nội dung',
      type: 'textarea',
      required: true,
    },
    {
      key: 'evaluation',
      label: 'Student feedback / Đánh giá',
      type: 'textarea',
    },
  ],
  lead: [
    { key: 'name', label: 'Student / Lead name', required: true },
    { key: 'parent', label: 'Parent' },
    { key: 'phone', label: 'Phone' },
    { key: 'classId', label: 'Interested class', type: 'class' },
    {
      key: 'status',
      label: 'Stage',
      type: 'select',
      options: [
        'New',
        'Contacted',
        'Trial booked',
        'Trial completed',
        'Enrolled',
        'Not proceeding',
      ],
    },
    { key: 'followUp', label: 'Follow up on', type: 'date' },
    { key: 'notes', label: 'Notes', type: 'textarea' },
  ],
  membership: [
    { key: 'studentId', label: 'Student', type: 'student', required: true },
    { key: 'classId', label: 'Class', type: 'class', required: true },
    { key: 'from', label: 'First lesson date', type: 'date', required: true },
    {
      key: 'until',
      label: 'Last lesson date (leave blank if continuing)',
      type: 'date',
    },
    {
      key: 'schedule',
      label: 'Timetable',
      type: 'select',
      options: ['Regular', 'Saturday'],
    },
  ],
  calendar: [
    { key: 'classId', label: 'Class', type: 'class', required: true },
    {
      key: 'date',
      label: 'Lesson / holiday date',
      type: 'date',
      required: true,
    },
    { key: 'open', label: 'Class takes place on this date', type: 'checkbox' },
    { key: 'reason', label: 'Holiday or timetable note', required: true },
  ],
  commitment: [
    { key: 'description', label: 'Recurring expense', required: true },
    { key: 'category', label: 'Category' },
    {
      key: 'amount',
      label: 'Expected amount (VND)',
      type: 'number',
      required: true,
    },
    {
      key: 'frequency',
      label: 'Frequency',
      type: 'select',
      options: ['Monthly', 'Quarterly', 'Annually', 'Other'],
    },
    { key: 'account', label: 'Account' },
    { key: 'dueDate', label: 'Next due date', type: 'date' },
    { key: 'notes', label: 'Notes', type: 'textarea' },
  ],
  reconciliation: [
    { key: 'account', label: 'Account', required: true },
    {
      key: 'opening',
      label: 'Opening statement balance (VND)',
      type: 'number',
      required: true,
    },
    {
      key: 'statementClosing',
      label: 'Closing statement balance (VND)',
      type: 'number',
      required: true,
    },
    { key: 'notes', label: 'Statement reference', type: 'textarea' },
  ],
  close: [
    {
      key: 'status',
      label: 'Month status',
      type: 'select',
      options: ['Closed', 'Open'],
    },
    {
      key: 'notes',
      label: 'Close or reopen notes',
      type: 'textarea',
      required: true,
    },
  ],
  payroll: [
    { key: 'month', label: 'Salary month', type: 'month', required: true },
    { key: 'name', label: 'Staff name', required: true },
    { key: 'position', label: 'Position' },
    {
      key: 'gross',
      label: 'Gross salary (VND)',
      type: 'number',
      required: true,
    },
    {
      key: 'deductions',
      label: 'Approved tax and deductions (VND)',
      type: 'number',
      required: true,
    },
    {
      key: 'employerInsurance',
      label: 'Employer insurance (VND)',
      type: 'number',
    },
    {
      key: 'status',
      label: 'Review status',
      type: 'select',
      options: ['Draft', 'Approved', 'Needs confirmation'],
    },
    { key: 'notes', label: 'Payroll notes', type: 'textarea' },
  ],
  task: [
    { key: 'title', label: 'Task', required: true },
    { key: 'date', label: 'Work date', type: 'date' },
    { key: 'dueDate', label: 'Due date', type: 'date' },
    {
      key: 'category',
      label: 'Category',
      type: 'select',
      options: [
        'Payroll',
        'Bank',
        'Student invoices',
        'Tax filing',
        'Contracts',
        'Admin',
        'Work log',
      ],
    },
    { key: 'assignedTo', label: 'Responsible person' },
    {
      key: 'status',
      label: 'Status',
      type: 'select',
      options: ['To do', 'In progress', 'Done', 'Logged in source'],
    },
    { key: 'notes', label: 'Details', type: 'textarea' },
  ],
  staff: [
    { key: 'name', label: 'Staff name', required: true },
    { key: 'email', label: 'Sign-in email', type: 'email', required: true },
    {
      key: 'role',
      label: 'Role',
      type: 'select',
      options: ['TA', 'Finance', 'Director'],
    },
    { key: 'active', label: 'Access enabled', type: 'checkbox' },
  ],
};
